//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("HL7Fuse")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0-unknown-branch.unknown-revision+DEVD1_20160829154604")]
[assembly: AssemblyCopyright("Copyright © MIT License 2016")]
[assembly: AssemblyTrademark("")]

